### TEST GET / WEBSITE

GET http://localhost:8000

### TEST GET /dashboard WEBSITE
GET http://localhost:8000/dashboard


### DATA ENDPOINT
GET http://localhost:8000/api/data

### DATA ENDPOINT FOR ADDING A USER
POST http://localhost:8000/api/data
Content-Type: application/json


{
    "name": "gerydw"
}

### DELETE END POINT 
DELETE http://localhost:8000/api/data